#!/usr/bin/env bash

docker build --tag tkin91e55/antlr:test .

#docker run -itd --entrypoint /bin/bash --name antlr --mount type=bind,source="$(pwd)"/antlr-mega-tutorial,target=/examples tkin91e55/antlr:test
docker run -itd --name antlr --mount type=bind,source="$(pwd)"/antlr-mega-tutorial,target=/examples tkin91e55/antlr:test /bin/bash
